### ISSUE TITLE
Issue when inputting data into field with add-on

### ISSUE THREAD

**Issue by avidrucker** [javdejong/nhk-pronunciation#1]
I was attempting to have the audio/pronunciation added for 二重盲検法 in the browser window, when my Expression field started flashing rapidly. No audio was added, and I got the following error message when I exited the browser window.

An error occurred. It may have been caused by a harmless bug, 
or your deck may have a problem. 
To confirm it's not a problem with your deck, please run Tools > Check Database. 
If that doesn't fix the problem, please copy the following
into a bug report:
Traceback (most recent call last):
  File "C:\cygwin\home\dae\win\build\pyi.win32\anki\outPYZ1.pyz/aqt.progress", line 69, in handler
  File "C:\cygwin\home\dae\win\build\pyi.win32\anki\outPYZ1.pyz/aqt.editor", line 468, in onUpdate
  File "C:\cygwin\home\dae\win\build\pyi.win32\anki\outPYZ1.pyz/aqt.editor", line 573, in checkValid
AttributeError: 'NoneType' object has no attribute 'fields'
Traceback (most recent call last):
  File "C:\cygwin\home\dae\win\build\pyi.win32\anki\outPYZ1.pyz/aqt.progress", line 69, in handler
  File "C:\cygwin\home\dae\win\build\pyi.win32\anki\outPYZ1.pyz/aqt.editor", line 468, in onUpdate
  File "C:\cygwin\home\dae\win\build\pyi.win32\anki\outPYZ1.pyz/aqt.editor", line 573, in checkValid
AttributeError: 'NoneType' object has no attribute 'fields'

**Comment by javdejong** [comment]
Closing this, as it's been 4+ years without any activity.
